### ISSUE TITLE
The register map of MPU9250 is wrong!

### ISSUE THREAD

**Issue by HBH-THU** [Seeed-Studio/Seeed_Arduino_IMU10DOF#1]
As i read the datasheet of MPU9250, it seems that the register map in MPU9250.h is wrong. The register map in  MPU9250.h is just a duplication of MPU9150.h(https://github.com/jrowberg/i2cdevlib/blob/master/Arduino/MPU9150/MPU9150.h), replacing the word from "MPU9150" to "MPU9250"!

**Comment by Pillar1989** [comment]
@HBH-THU  Sorry for replying to you so late. Could you specifically point out what is wrong?
